# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc720d7df48ea5c8f8bd23467c1896864e7433f5ed839a169edef467ebd76146c0a345a8e7ae64bbf624e704d0b0637af4c280e2ae3c0942ad9ee6683c825de9

test:
  secret_key_base: 39081ff80d4242efd56e1998f9356c920d6c422d699d316d0fe750df55a15c86ebfa287512f55a12019c4ae2fd09260966558cb279fb5c6e785dc6620cb0517b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
